/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.com.witsoft.frames;

import co.com.witsoft.classes.Calculate;
import javax.swing.JLabel;
import javax.swing.JSpinner;

/**
 *
 * @author EQUIPO
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    
    private Calculate calculate;
    
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        neighbour_1 = new javax.swing.JSpinner();
        neighbour_2 = new javax.swing.JSpinner();
        neighbour_3 = new javax.swing.JSpinner();
        neighbour_4 = new javax.swing.JSpinner();
        neighbour_5 = new javax.swing.JSpinner();
        neighbour_6 = new javax.swing.JSpinner();
        neighbour_7 = new javax.swing.JSpinner();
        neighbour_8 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        number_days = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        previus_day_1 = new javax.swing.JLabel();
        previus_day_2 = new javax.swing.JLabel();
        previus_day_3 = new javax.swing.JLabel();
        previus_day_4 = new javax.swing.JLabel();
        previus_day_5 = new javax.swing.JLabel();
        previus_day_6 = new javax.swing.JLabel();
        previus_day_7 = new javax.swing.JLabel();
        previus_day_8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        next_day = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        next_day_2 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        next_day_3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        next_day_4 = new javax.swing.JLabel();
        next_day_5 = new javax.swing.JLabel();
        next_day_6 = new javax.swing.JLabel();
        next_day_7 = new javax.swing.JLabel();
        next_day_8 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        next_day_1 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        previus_day = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vecinos Envidiosos - WitSoft");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Configuración", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 11))); // NOI18N

        neighbour_1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        neighbour_1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1, 1));
        neighbour_1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vecino 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 11))); // NOI18N

        neighbour_2.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        neighbour_2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1, 1));
        neighbour_2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vecino 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 11))); // NOI18N

        neighbour_3.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        neighbour_3.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1, 1));
        neighbour_3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vecino 3", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 11))); // NOI18N

        neighbour_4.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        neighbour_4.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1, 1));
        neighbour_4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vecino 4", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 11))); // NOI18N

        neighbour_5.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        neighbour_5.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1, 1));
        neighbour_5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vecino 5", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 11))); // NOI18N

        neighbour_6.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        neighbour_6.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1, 1));
        neighbour_6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vecino 6", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 11))); // NOI18N

        neighbour_7.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        neighbour_7.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1, 1));
        neighbour_7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vecino 7", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 11))); // NOI18N

        neighbour_8.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        neighbour_8.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1, 1));
        neighbour_8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vecino 8", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 11))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setText("  0  ");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Vecino 0"));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("  0  ");
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Vecino 9"));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel3.setText("Numero de días:");

        number_days.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        number_days.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(neighbour_1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(neighbour_2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(neighbour_3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(neighbour_4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(neighbour_5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(neighbour_6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(neighbour_7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(neighbour_8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGap(0, 55, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(number_days, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(neighbour_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(neighbour_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(neighbour_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(neighbour_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(neighbour_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(neighbour_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(neighbour_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(neighbour_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(number_days, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(11, 212, 11));
        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Iniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 11))); // NOI18N

        jLabel4.setBackground(new java.awt.Color(75, 233, 75));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("  0  ");
        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder("V 0"));
        jLabel4.setOpaque(true);

        previus_day_1.setBackground(new java.awt.Color(75, 233, 75));
        previus_day_1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        previus_day_1.setText("  0  ");
        previus_day_1.setBorder(javax.swing.BorderFactory.createTitledBorder("V 1"));
        previus_day_1.setOpaque(true);

        previus_day_2.setBackground(new java.awt.Color(75, 233, 75));
        previus_day_2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        previus_day_2.setText("  0  ");
        previus_day_2.setBorder(javax.swing.BorderFactory.createTitledBorder("V 2"));
        previus_day_2.setOpaque(true);

        previus_day_3.setBackground(new java.awt.Color(75, 233, 75));
        previus_day_3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        previus_day_3.setText("  0  ");
        previus_day_3.setBorder(javax.swing.BorderFactory.createTitledBorder("V 3"));
        previus_day_3.setOpaque(true);

        previus_day_4.setBackground(new java.awt.Color(75, 233, 75));
        previus_day_4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        previus_day_4.setText("  0  ");
        previus_day_4.setBorder(javax.swing.BorderFactory.createTitledBorder("V 4"));
        previus_day_4.setOpaque(true);

        previus_day_5.setBackground(new java.awt.Color(75, 233, 75));
        previus_day_5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        previus_day_5.setText("  0  ");
        previus_day_5.setBorder(javax.swing.BorderFactory.createTitledBorder("V 5"));
        previus_day_5.setOpaque(true);

        previus_day_6.setBackground(new java.awt.Color(75, 233, 75));
        previus_day_6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        previus_day_6.setText("  0  ");
        previus_day_6.setBorder(javax.swing.BorderFactory.createTitledBorder("V 6"));
        previus_day_6.setOpaque(true);

        previus_day_7.setBackground(new java.awt.Color(75, 233, 75));
        previus_day_7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        previus_day_7.setText("  0  ");
        previus_day_7.setBorder(javax.swing.BorderFactory.createTitledBorder("V 7"));
        previus_day_7.setOpaque(true);

        previus_day_8.setBackground(new java.awt.Color(75, 233, 75));
        previus_day_8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        previus_day_8.setText("  0  ");
        previus_day_8.setBorder(javax.swing.BorderFactory.createTitledBorder("V 8"));
        previus_day_8.setOpaque(true);

        jLabel13.setBackground(new java.awt.Color(75, 233, 75));
        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setText("  0  ");
        jLabel13.setBorder(javax.swing.BorderFactory.createTitledBorder("V 9"));
        jLabel13.setOpaque(true);

        next_day.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        next_day.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        next_day.setText("0");
        next_day.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("<= Dia anterior");

        next_day_2.setBackground(new java.awt.Color(75, 233, 75));
        next_day_2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        next_day_2.setText("  0  ");
        next_day_2.setBorder(javax.swing.BorderFactory.createTitledBorder("V 2"));
        next_day_2.setOpaque(true);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        next_day_3.setBackground(new java.awt.Color(75, 233, 75));
        next_day_3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        next_day_3.setText("  0  ");
        next_day_3.setBorder(javax.swing.BorderFactory.createTitledBorder("V 3"));
        next_day_3.setOpaque(true);

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Dia siguiente =>");

        next_day_4.setBackground(new java.awt.Color(75, 233, 75));
        next_day_4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        next_day_4.setText("  0  ");
        next_day_4.setBorder(javax.swing.BorderFactory.createTitledBorder("V 4"));
        next_day_4.setOpaque(true);

        next_day_5.setBackground(new java.awt.Color(75, 233, 75));
        next_day_5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        next_day_5.setText("  0  ");
        next_day_5.setBorder(javax.swing.BorderFactory.createTitledBorder("V 5"));
        next_day_5.setOpaque(true);

        next_day_6.setBackground(new java.awt.Color(75, 233, 75));
        next_day_6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        next_day_6.setText("  0  ");
        next_day_6.setBorder(javax.swing.BorderFactory.createTitledBorder("V 6"));
        next_day_6.setOpaque(true);

        next_day_7.setBackground(new java.awt.Color(75, 233, 75));
        next_day_7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        next_day_7.setText("  0  ");
        next_day_7.setBorder(javax.swing.BorderFactory.createTitledBorder("V 7"));
        next_day_7.setOpaque(true);

        next_day_8.setBackground(new java.awt.Color(75, 233, 75));
        next_day_8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        next_day_8.setText("  0  ");
        next_day_8.setBorder(javax.swing.BorderFactory.createTitledBorder("V 8"));
        next_day_8.setOpaque(true);

        jLabel25.setBackground(new java.awt.Color(75, 233, 75));
        jLabel25.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel25.setText("  0  ");
        jLabel25.setBorder(javax.swing.BorderFactory.createTitledBorder("V 9"));
        jLabel25.setOpaque(true);

        jLabel26.setBackground(new java.awt.Color(75, 233, 75));
        jLabel26.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel26.setText("  0  ");
        jLabel26.setBorder(javax.swing.BorderFactory.createTitledBorder("V 0"));
        jLabel26.setOpaque(true);

        next_day_1.setBackground(new java.awt.Color(75, 233, 75));
        next_day_1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        next_day_1.setText("  0  ");
        next_day_1.setBorder(javax.swing.BorderFactory.createTitledBorder("V 1"));
        next_day_1.setOpaque(true);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        previus_day.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        previus_day.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        previus_day.setText("0");
        previus_day.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(next_day_1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(next_day_2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(next_day_3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(next_day_4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(next_day_5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(next_day_6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(next_day_7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(next_day_8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel25))
                            .addComponent(next_day, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(previus_day_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(previus_day_2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(previus_day_3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(previus_day_4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(previus_day_5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(previus_day_6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(previus_day_7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(previus_day_8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(previus_day, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(previus_day))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(previus_day_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(previus_day_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(previus_day_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(previus_day_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(previus_day_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(previus_day_6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(previus_day_7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(previus_day_8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(next_day))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(next_day_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(next_day_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(next_day_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(next_day_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(next_day_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(next_day_6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(next_day_7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(next_day_8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // cargar los coomponentes necesarios para la clase calcular
        this.calculate =  new Calculate();
        this.calculate.setNeighbors(new JSpinner[]{
            neighbour_1, 
            neighbour_2, 
            neighbour_3, 
            neighbour_4, 
            neighbour_5, 
            neighbour_6, 
            neighbour_7, 
            neighbour_8
        });
        this.calculate.setNumberDays(number_days);
        this.calculate.setLabelsDays( new JLabel[]{
            previus_day,
            next_day
        });
        this.calculate.setStatusPreviusDays(new JLabel[]{
            previus_day_1,
            previus_day_2,
            previus_day_3,
            previus_day_4,
            previus_day_5,
            previus_day_6,
            previus_day_7,
            previus_day_8
        });
        this.calculate.setStatusNextDays(new JLabel[]{
            next_day_1,
            next_day_2,
            next_day_3,
            next_day_4,
            next_day_5,
            next_day_6,
            next_day_7,
            next_day_8
        });
        
        this.calculate.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSpinner neighbour_1;
    private javax.swing.JSpinner neighbour_2;
    private javax.swing.JSpinner neighbour_3;
    private javax.swing.JSpinner neighbour_4;
    private javax.swing.JSpinner neighbour_5;
    private javax.swing.JSpinner neighbour_6;
    private javax.swing.JSpinner neighbour_7;
    private javax.swing.JSpinner neighbour_8;
    private javax.swing.JLabel next_day;
    private javax.swing.JLabel next_day_1;
    private javax.swing.JLabel next_day_2;
    private javax.swing.JLabel next_day_3;
    private javax.swing.JLabel next_day_4;
    private javax.swing.JLabel next_day_5;
    private javax.swing.JLabel next_day_6;
    private javax.swing.JLabel next_day_7;
    private javax.swing.JLabel next_day_8;
    private javax.swing.JSpinner number_days;
    private javax.swing.JLabel previus_day;
    private javax.swing.JLabel previus_day_1;
    private javax.swing.JLabel previus_day_2;
    private javax.swing.JLabel previus_day_3;
    private javax.swing.JLabel previus_day_4;
    private javax.swing.JLabel previus_day_5;
    private javax.swing.JLabel previus_day_6;
    private javax.swing.JLabel previus_day_7;
    private javax.swing.JLabel previus_day_8;
    // End of variables declaration//GEN-END:variables
}
